name: g4stab_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.26.4
  - pandas=2.2.3
  - matplotlib=3.9.2
  - scikit-learn=1.5.2
  - tqdm=4.66.5
  - pip=24.2
  - pip:
      - tensorflow==2.16.1
